### ISSUE TITLE
build xapian index failed

### ISSUE THREAD

**Issue by plutoid** [moinwiki/moin-1.9#41]
hi,

I failed to build xapian index for moin, not sure what kind of this issue, any suggestions for this? thanks a lot!

env: 
xapian-bindings 1.2.22
moinmoin: 1.9.8
Python 2.7.12
```
python /usr/lib/python2.7/dist-packages/MoinMoin/script/moin.py  \
  --config-dir=/home/nginx/pyenv/wiki/ --wiki-url=http://localhost/  \
  index build --mode=buildnewindex 

2019-03-26 16:55:43,250 INFO MoinMoin.log:151 using logging configuration read from built-in fallback in MoinMoin.log module
2019-03-26 16:55:43,250 INFO MoinMoin.log:157 Running MoinMoin 1.9.8 release code from /usr/lib/python2.7/dist-packages/MoinMoin
2019-03-26 16:55:49,960 INFO MoinMoin.config.multiconfig:127 using wiki config: /home/nginx/pyenv/wiki/wikiconfig.pyc
2019-03-26 16:56:02,198 INFO MoinMoin.search.Xapian.indexing:580 indexing 460 pages...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/MoinMoin/script/moin.py", line 26, in <module>
    run()
  File "/usr/lib/python2.7/dist-packages/MoinMoin/script/moin.py", line 17, in run
    MoinScript().run(showtime=0)
  File "/usr/lib/python2.7/dist-packages/MoinMoin/script/__init__.py", line 138, in run
    self.mainloop()
  File "/usr/lib/python2.7/dist-packages/MoinMoin/script/__init__.py", line 266, in mainloop
    plugin_class(args[2:], self.options).run() # all starts again there
  File "/usr/lib/python2.7/dist-packages/MoinMoin/script/__init__.py", line 138, in run
    self.mainloop()
  File "/usr/lib/python2.7/dist-packages/MoinMoin/script/index/build.py", line 86, in mainloop
    self.command()
  File "/usr/lib/python2.7/dist-packages/MoinMoin/script/index/build.py", line 115, in command
    idx.indexPages(self.files, idx_mode)
  File "/usr/lib/python2.7/dist-packages/MoinMoin/search/builtin.py", line 212, in indexPages
    self._index_pages(request, files, mode, pages=pages)
  File "/usr/lib/python2.7/dist-packages/MoinMoin/search/Xapian/indexing.py", line 582, in _index_pages
    self._index_page(request, connection, pagename, mode=mode)
  File "/usr/lib/python2.7/dist-packages/MoinMoin/search/Xapian/indexing.py", line 372, in _index_page
    updated = self._index_page_rev(request, connection, pagename, revno, mode=mode)
  File "/usr/lib/python2.7/dist-packages/MoinMoin/search/Xapian/indexing.py", line 404, in _index_page_rev
    mtime = page.mtime_usecs()
  File "/usr/lib/python2.7/dist-packages/MoinMoin/Page.py", line 694, in mtime_usecs
    entry = self.editlog_entry()
  File "/usr/lib/python2.7/dist-packages/MoinMoin/Page.py", line 532, in editlog_entry
    for entry in edit_log.reverse():
  File "/usr/lib/python2.7/dist-packages/MoinMoin/logfile/__init__.py", line 116, in reverse
    result = self.previous()
  File "/usr/lib/python2.7/dist-packages/MoinMoin/logfile/__init__.py", line 323, in previous
    result = self.__previous()
  File "/usr/lib/python2.7/dist-packages/MoinMoin/logfile/__init__.py", line 312, in __previous
    return self.parser(self.__buffer.lines[self.__rel_index])
  File "/usr/lib/python2.7/dist-packages/MoinMoin/logfile/editlog.py", line 226, in parser
    result.ed_time_usecs = long(result.ed_time_usecs or '0') # has to be long for py 2.2.x
UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-107: invalid decimal Unicode string
```
some index files generated as below, not sure should I ignore this or not.

```
(pyenv) root@PVGN56589222A:/home/nginx/pyenv/wiki# ls xapian_indx_dir/wikiconfig/index.new/flintlock  position.baseA  position.DB     postlist.baseB  record.baseA  record.DB       spelling.baseB  termlist.baseA  termlist.DBiamchert   position.baseB  postlist.baseA  postlist.DB     record.baseB  spelling.baseA  spelling.DB     termlist.baseB
..
18M     xapian_indx_dir/wikiconfig/index.new
```

Best regards,
Hua

**Comment by ThomasWaldmann** [comment]
The traceback means that the edit-log of the page is corrupted.

You could just load it into an editor and remove the corrupt line(s).

**Comment by plutoid** [comment]
change below line 226, and it works now, looks it's not compatible with Python 2.7.12.

```
/usr/lib/python2.7/dist-packages/MoinMoin/logfile/editlog.py
result.ed_time_usecs = long(result.ed_time_usecs or '0')  -> 
result.ed_time_usecs = (result.ed_time_usecs or '0')
```

```
(pyenv) root@PVGN56589222A:/home/nginx/pyenv/wiki# python /usr/lib/python2.7/dist-packages/MoinMoin/script/moin.py  --config-dir=/home/nginx/pyenv/wiki/ --wiki-url=http://localhost/  index build --mode=buildnewindex
2019-03-27 14:10:50,724 INFO MoinMoin.log:151 using logging configuration read from built-in fallback in MoinMoin.log module
2019-03-27 14:10:50,724 INFO MoinMoin.log:157 Running MoinMoin 1.9.8 release code from /usr/lib/python2.7/dist-packages/MoinMoin2019-03-27 14:10:54,869 INFO MoinMoin.config.multiconfig:127 using wiki config: /home/nginx/pyenv/wiki/wikiconfig.pyc
2019-03-27 14:11:00,771 INFO MoinMoin.search.Xapian.indexing:580 indexing 460 pages...
2019-03-27 14:11:42,320 INFO MoinMoin.search.builtin:214 indexing completed successfully in 47.29 seconds.
```

**Comment by ThomasWaldmann** [comment]
@plutoid that change is incorrect and just hides the real problem, which i already pointed to.
