### ISSUE TITLE
Install fails due to decoding error on python2

### ISSUE THREAD

**Issue by flazzarini** [moinwiki/moin-1.9#49]
This issue has already been reported by #40, however I am still having the issue to install `moin==1.9.10` on a python2 Virtual Environment on Ubuntu 16.04. Commit 4a708cd49630b56a54e14072ee52140713b283d7 has been merged onto master but hasn't been released yet.

If I download the tarball for version 1.9.10 the UTF-8 Character is still present in the `setup.cfg` and `setup.py`.

As already mentioned in ticket #40 here the output I get when trying to install moin==1.9.10 in a python2 virtual environment.

```
$ ./env/bin/pip install moin==1.9.10
Looking in indexes: https://pypi.org/simple, https://devpi.dtt.ptech.lu/coss/public
Collecting moin==1.9.10
  Using cached moin-1.9.10.tar.gz (37.3 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/users/frank/workspace/ipswiki/env/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-keXHzx/moin/setup.py'"'"'; __file__='"'"'/tmp/pip-install-keXHzx/moin/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-keXHzx/moin/pip-egg-info
         cwd: /tmp/pip-install-keXHzx/moin/
    Complete output (17 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-keXHzx/moin/setup.py", line 355, in <module>
        setup(**setup_args)
      File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
        dist.parse_config_files()
      File "/home/users/frank/workspace/ipswiki/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 699, in parse_config_files
        self._parse_config_files(filenames=filenames)
      File "/home/users/frank/workspace/ipswiki/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 596, in _parse_config_files
        (parser.read_file if six.PY3 else parser.readfp)(reader)
      File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
        self._read(fp, filename)
      File "/usr/lib/python2.7/ConfigParser.py", line 479, in _read
        line = fp.readline()
      File "/home/users/frank/workspace/ipswiki/env/lib/python2.7/codecs.py", line 314, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 57: invalid start byte
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Pip Version used: 20.0.1

**Comment by ThomasWaldmann** [comment]
It's not a utf-8 byte sequence (the utf-8 decoder would not fail if it was one).

I suspect it is iso-8859-1.

**Comment by ThomasWaldmann** [comment]
And the problem was already fixed, see #40 

TODO: make a new release to get the fix out.

**Comment by ThomasWaldmann** [comment]
@flazzarini i've done some upgrades to master branch, can you test?

**Comment by ThomasWaldmann** [comment]
closing this due to #40. a release with this might also come rather soon.
