### ISSUE TITLE
mailimport not working

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin-1.9#53]
```
MoinMoin.xmlrpc.ProcessMail ERROR An error occurred while processing the message: ("No suitable user found for mail address u'Mustermann'",)
MoinMoin.wsgiapp ERROR An exception has occurred [https://info.*.*/?action=xmlrpc2].
Traceback (most recent call last):
File "/srv/moin-1.9/MoinMoin/wsgiapp.py", line 264, in __call__
     response = run(context)
File "/srv/moin-1.9/MoinMoin/wsgiapp.py", line 90, in run
     context.cfg.session_service.finalize(context, context.session)
File "/srv/moin-1.9/MoinMoin/web/session.py", line 179, in finalize
     if request.user.auth_method == 'setuid':
AttributeError: 'NoneType' object has no attribute 'auth_method'
```

**Comment by ThomasWaldmann** [comment]
Happens for the xmlrpc call made by wikimailimport.

**Comment by ThomasWaldmann** [comment]
> No suitable user found for mail address u'Mustermann'

This is likely the main issue why the mail import does not work.

**Comment by ThomasWaldmann** [comment]
> From: =?utf-8?B?S29xxxxxxxxxxxx=?= <xx@xxx.xxx>

The email address looks like this.

**Comment by ThomasWaldmann** [comment]
So we have 2 issues here:
1. issue due to utf-8 encoded name and our code not finding a wiki user for the mail address
2. auth_method AttributeError as a secondary error

**Comment by ThomasWaldmann** [comment]
The problem is:
- realname contains a comma
- realname is not within double-quotes

>>> getaddresses([u'From: Mustermann, Hans <hm@example.org>'])
[('', u'Mustermann'), (u'Hans', u'hm@example.org')]

>>> getaddresses([u'From: "Mustermann, Hans" <hm@example.org>'])
[(u'Mustermann, Hans', u'hm@example.org')]
