### ISSUE TITLE
pip install moin fails

### ISSUE THREAD

**Issue by pathway** [moinwiki/moin-1.9#56]
- ubuntu 18.04
- pip 19.0.3
- Python 3.6.7

```
(tfgpu1) robin@thor:/SRC/pathway$ pip install moin
Collecting moin
  Using cached https://files.pythonhosted.org/packages/db/c4/58872c31f3c242c2cec3a35f493628182979b664645858dafba4071b9cb5/moin-1.9.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-enx51tia/moin/setup.py", line 68
        def visit((prefix, strip, found), dirname, names):
                  ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-enx51tia/moin/
```

**Comment by ThomasWaldmann** [comment]
moin 1.9 requires python 2.7.x.
